### ISSUE TITLE
Error para instalar la base de datos: "Unknown collation: utf8mb4_09000_ai_ci"

### ISSUE THREAD

**Issue by AlfredoGIIB** [andres-alvarado/beisbol-analitica#104]
En la instalación de la base de datos ocurrió el siguiente error al ejecutar el archivo [dump.sql](https://drive.google.com/file/d/1JVlT-JqOpyf2zxhSZWvOEVNKHXyF58Wk/view) : "Unknown collation: utf8mb4_09000_ai_ci"
### Solución: 
Abrir el fichero _dump.sql_ mediante un editor (recomendamos [Notepad++ 7.9.3 Release](https://notepad-plus-plus.org/downloads/v7.9.3/)) y reemplazar **utf8mb4_09000_ai_ci**  por **utf8mb4_general_ci**
Guardar cambios y volver a ejecutar el archivo _dump.sql_

**Comment by juanitobanca** [comment]
Gracias, en posterioreres versiones removeremos estas lineas. Ya son varias las personas que nos la han comentado.
