### ISSUE TITLE
[ Park Factors ] Calcular Park Factors para Carreras

### ISSUE THREAD

**Issue by juanitobanca** [andres-alvarado/beisbol-analitica#13]
Resumen
---
Neesitamos crear tablas y procedimientos para los factores de parque basicos. Empecemos con Carreras.

Codigo Muestra
---
```
# Agrupaciones en agg_batting_stats
Select Distinct grouping_id, grouping_description
  From agg_batting_stats;

# Query
With home AS 
(
  Select majorLeagueId, seasonId, venueId, teamId, runs
  From agg_batting_stats
  Where grouping_id = 126
  And gameType2 = 'RS'
  And teamType = 'home'
), away AS 
(
  Select majorLeagueId, seasonId, venueId, teamId, runs
  From agg_batting_stats
  Where grouping_id = 122
  And gameType2 = 'RS'
  And teamType = 'away'
)
Select h.majorLeagueId, h.seasonId, h.venueId, h.teamId, h.runs, a.runs
From home h 
Inner Join away a 
On h.seasonId = a.seasonId
And h.majorLeagueId = a.majorLeagueId
And h.teamId = a.teamId
```

Recursos
---
https://en.wikipedia.org/wiki/Batting_park_factor

**Comment by andres-alvarado** [comment]
@omargoldpr, hazme saber si tienes alguna duda y si necesitas revision de codigo.

**Comment by juanitobanca** [comment]
@IvanVC21, si vas a trabajar en este issue, primero hay que solucionar el issue #42

**Comment by IvanVC21** [comment]
> @IvanVC21, si vas a trabajar en este issue, primero hay que solucionar el issue #42

Enterado!

**Comment by IvanVC21** [comment]
Para trabajar en este issue se requiere terminar la tarea #1

**Comment by juanitobanca** [comment]
Debemos pensar detenidamente este calculo, ya que ademas de carreras, requeriremos otros datos como: hits, homeruns, flies, fouls(?), strikeOuts(?). Ademas de esto hay diferentes enfoques para calcular los parkFactors. Empecemos con un enfoque sencillo pero considerando lo que aqui se menciona.

**Comment by juanitobanca** [comment]
@IvanVC21, para empezar el PF de carreras, se puede usar la tabla de games, hazme saber si tienes dudas:
```
Select  gamePk, venueId, teamId, homeScore, awayScore
From games
limit 20
```
