### ISSUE TITLE
[ TRADUCCION ][Hidden Game of Baseball ] Resumen de Capitulo 5 

### ISSUE THREAD

**Issue by juanitobanca** [andres-alvarado/beisbol-analitica#18]
Recursos
---
Resumen en ingles: https://juanitobanca.com/2020/03/30/the-hidden-game-of-baseball-capitulo-5/

**Comment by luisamparou** [comment]
Aquí dejo la traducción del capítulo:

[The Hidden Game of Baseball_ Capitulo 5 - Traducción resumen.docx](https://github.com/andres-alvarado/beisbol-analitica/files/5720688/The.Hidden.Game.of.Baseball_.Capitulo.5.-.Traduccion.resumen.docx)


> ## Recursos
> Resumen en ingles: https://juanitobanca.com/2020/03/30/the-hidden-game-of-baseball-capitulo-5/

**Comment by juanitobanca** [comment]
Gracias por tu esfuerzo @luisamparou  !

**Comment by luisamparou** [comment]
> Gracias por tu esfuerzo @luisamparou  !

¡Siempre!
