### ISSUE TITLE
[ TRADUCCION ] Resumen de Capitulo 6 

### ISSUE THREAD

**Issue by juanitobanca** [andres-alvarado/beisbol-analitica#19]
Recursos
---
Resumen en ingles: https://juanitobanca.com/2020/06/05/the-hidden-game-of-baseball-capitulo-6/

**Comment by belgrades** [comment]
Envío esto mañana

**Comment by juanitobanca** [comment]
Gracias @belgrades.

**Comment by IvanVC21** [comment]
[Capitulo 6 The Hidden Game of Baseball.docx](https://github.com/andres-alvarado/beisbol-analitica/files/5811015/Capitulo.6.The.Hidden.Game.of.Baseball.docx)

**Comment by juanitobanca** [comment]
Gracias @belgrades  e @IvanVC21 !
