### ISSUE TITLE
[ PREGUNTA ] Deberiamos agregar resumenes de libros a este repositorio?

### ISSUE THREAD

**Issue by juanitobanca** [andres-alvarado/beisbol-analitica#21]
Resumen
---
Como parte de este proyecto/movimiento nos gustaria traducir resumenes de diferentes libros que no se encuentran disponibles en español.  La pregunta es, deberiamos agregarlos a este repositorio o deberiamos crear otro?

**Comment by junger92** [comment]
me parece bien añadirlos en este repositorio
