### ISSUE TITLE
Problema en documentación de Instalación de la Base de Datos en Windows

### ISSUE THREAD

**Issue by junger92** [andres-alvarado/beisbol-analitica#26]
en  [https://github.com/andres-alvarado/beisbol-analitica/wiki/Instalaci%C3%B3n-de-la-Base-de-Datos.](url) en el paso 7 luego de crear la base de datos y antes de cargar el archivo dump.sql es necesario hacer:
`use nombre_de_la_base_de_datos`

**Comment by juanitobanca** [comment]
Arreglado. Gracias @junger92:
https://github.com/andres-alvarado/beisbol-analitica/wiki/Instalaci%C3%B3n-de-la-Base-de-Datos.
