### ISSUE TITLE
Agregar soporte con Docker para instalar la base de datos

### ISSUE THREAD

**Issue by belgrades** [andres-alvarado/beisbol-analitica#28]
Sería útil para usuarios con menos experiencia usar Docker en vez de configurar toda la BD. La serie de tareas mínimas requeridas son:

- [ ] Agregar nuestra imagen al Docker Registry
- [ ] Colocar ejemplo con docker pull
- [ ] Colocar ejemplo con docker-compose
- [ ] Colocar ejemplo usando MySQL WorkBench y/o DBeaver
- [ ] Agregar página relativa a este issue en el Wiki
- [ ] Agregar explicación para instalar Docker

**Comment by juanitobanca** [comment]
Gracias @belgrades !
