### ISSUE TITLE
Agregar un branch de desarrollo

### ISSUE THREAD

**Issue by belgrades** [andres-alvarado/beisbol-analitica#29]
No tiene sentido agregar un branch de desarrollo y luego hacer pull requests hacia `main`? Se puede salir de control el desarrollo si no se organiza eso.

**Comment by juanitobanca** [comment]
Hola @belgrades , no habia tenido tiempo de entrar al proyecto por fiestas. Hagamoslo. Podrias tomar ownership de esto?

**Comment by juanitobanca** [comment]
Agregado el branch de development.
