### ISSUE TITLE
[ Heat Maps ] Seccionar el diamante en diferentes cuadrantes

### ISSUE THREAD

**Issue by juanitobanca** [andres-alvarado/beisbol-analitica#3]
Resumen
---
Una parte importante del analisis del beisbol incluye en crear mapas de calor para analizar tendencias. Para poder hacer esto debemos calcular algunas ecuaciones de rectas que nos permitan seccionar el diamante en n partes ( supongamos 4 ).  Para poder encontrar las ecuaciones debemos considerar lo siguiente:

1. La MLB provee en los puntos *x* y *y* de donde cae la pelota. 
2. El origen ( es decir el homeplate ) esta situado aproximademente en el punto ( 0, 0 ) o ( 0,45 ). 
3. Las lineas de foul abren a 45 grados.
3. El valor maximo que pueden tener *x* y *y* es de 250.
4. Probablemente haya que convertir a coordenadas polares para encontrar las ecuaciones.

Pendiente
---
Agregar muestra de datos.

Recursos
---

Mas informacion: https://juanitobanca.com/2016/11/06/draft-baseball-seriesplotting-balls-in-play/

Resultado esperado:
<img width="1202" alt="Screen Shot 2020-12-07 at 6 07 48 PM" src="https://user-images.githubusercontent.com/15705246/101429167-1fe1e280-38b7-11eb-99ce-42961713fb92.png">

**Comment by juanitobanca** [comment]
Asignando a @lukisaias.

**Comment by lukisaias** [comment]
Buenas tardes Andrés, discúlpame que no he podido hacer nada. En realidad estoy nulo hasta ahora.

**Comment by juanitobanca** [comment]
> Buenas tardes Andrés, discúlpame que no he podido hacer nada. En realidad estoy nulo hasta ahora.

No te preocupes @lukisaias , hazme saber si tienes alguna duda.

**Comment by lukisaias** [comment]
buenas tardes Andres, necesito empezar desde cero.

**Comment by juanitobanca** [comment]
Claro @lukisaias, gracias. Dime, que duda tienes ?

**Comment by lukisaias** [comment]
No manejo bien la plataforma Github y mi conocimiento de SQL es muy básico. pero me interesa aprender

**Comment by juanitobanca** [comment]
Ok @lukisaias - Esta tarea no requiere SQL o Github. Para esta tarea solo necesitamos formular algunas ecuaciones: Revisa la descripcion inicial. Lo que queremos es particionar el campo de beisbol en cuatro partes. Las lineas de foul abren en 45 grados a partir de la coordenada (0,0). Por lo que segun yo, una linea debe particionar la parte derecha del campo en el angulo 45 + ( 45 / 2 ) y otra linea debe particionar la parte izquierda en el angulo 90 + ( 45 / 2 ). Hay que calcular las ecuaciones de recta.

**Comment by juanitobanca** [comment]
Estas son las ecuaciones
Linea de foul de primera base:
```
y = x
```
Linea de foul entre el center field y la linea de foul de primera base:
```
y = 2.414214 * x
```
Linea de foul entre el center field y la linea de foul de tercera base:
```
y = -2.414214 * x
```
Linea de foul de tercera base:
```
y = - x
```
Aca el codigo que calcula las ecuaciones de recta para seccionar el diamante, esta hecho en R
```
library('ggplot2')

# y = mx + b
# y = ( tang ( angulo) ) x + b
# Ya que el punto pasa por 0,0 entonces
# b = 0 y por lo tanto
# y = ( tang ( angulo) ) x 


eq1 = 45
a1 = data.frame( x = seq( 0, 150, 0.5 ))
a1$y = a1$x * tan(eq1*pi/180)

eq2 = 45 + ( 90 - 45) / 2
a2 = data.frame( x = seq( 0,  100 , 0.5 ))
a2$y = a2$x * tan(eq2*pi/180)

eq3 = 90 + ( 135 - 90) / 2
a3 = data.frame( x = seq( 0,  -100 , -0.5 ))
a3$y = a3$x * tan(eq3*pi/180)

eq4 = 135
a4 = data.frame( x = seq( 0,  -150 , -0.5 ))
a4$y = a4$x * tan(eq4*pi/180)

a5 = data.frame( x = rep( 0,  0 , 251 ), y = seq( 0,  250 , 1 ))

(
  ggplot()
+ geom_point( data  = a1, mapping = aes( x = x, y = y ), color = 'black')
+ geom_point( data  = a2, mapping = aes( x = x, y = y ), color = 'red')
+ geom_point( data  = a3, mapping = aes( x = x, y = y ), color = 'red')
+ geom_point( data  = a4, mapping = aes( x = x, y = y ), color = 'black')
+ geom_point( data  = a5, mapping = aes( x = x, y = y ), color = 'green')
+ theme_bw()
  
)
```
El codigo genera:
<img width="691" alt="Screen Shot 2021-01-28 at 7 57 56 PM" src="https://user-images.githubusercontent.com/15705246/106229812-1f711400-61a3-11eb-88cf-fabb49a2b951.png">

**Comment by lukisaias** [comment]
ok, ya veo.
