### ISSUE TITLE
Comprobar formulas de metricas de Bateo.

### ISSUE THREAD

**Issue by juanitobanca** [andres-alvarado/beisbol-analitica#37]
Descripcion
---

Hace poco acabamos de calcular datos a nivel [ liga, temporada], [liga, temporada, equipo], entre otros. Hay que comprobar que las formulas que se utilizaron para calcular las metricas son correctas. Lineas 99 a 151 de [este codigo](https://github.com/andres-alvarado/beisbol-analitica/blob/main/data/agregados/procedimientos/agg_batting_stats.sql)

**Comment by IvanVC21** [comment]
Yo me encargo de esta tarea.

**Comment by juanitobanca** [comment]
Gracias @IvanVC21 !,  tomate tu tiempo.

**Comment by IvanVC21** [comment]
Incorrectas:

- stolenBasePercentage (Linea 111): cambiar a stolenBases / (caughtStealing + stolenBases)
- battedBallsInPlayPercentage (Linea 149): cambiar a (singles + doubles + triples) / (atBats - strikeOuts - homeRuns + sacFlies)

Todo lo demás esta bien.

**Comment by juanitobanca** [comment]
Gracias @IvanVC21 , corregido.
