### ISSUE TITLE
[ Fildeo ] Agregar Estadisticas por Posicion y Jugador

### ISSUE THREAD

**Issue by juanitobanca** [andres-alvarado/beisbol-analitica#5]
Resumen
---
Tenemos informacion acerca de las posiciones que jugaron los peloteros durante un partido. Asi mismo, tambien tenemos los putouts, asistencias, errores y otra informacion por posicion jugada. No estoy seguro si debemos agregar esta data a distintos niveles como lo estamos haciendo para pitcheo y bateo. Para llevar esto a cabo necesitamos utilizar la tabla de `fielding_credits` mas la tabla de `game_player_fielding_stats`.

Recursos
---
Estadisticas que podemos calcular:
http://m.mlb.com/glossary/standard-stats
https://sabr.org/journal/article/measuring-defense-entering-the-zones-of-fielding-statistics/
http://www.espn.com/mlb/stats/fielding/_/order/true
https://gamechanger.zendesk.com/hc/en-us/articles/214493683-Stats-for-Batting-Pitching-Fielding-Catching
https://www.sportsbettingdime.com/guides/resources/baseball-stat-abbreviations/
https://www.baseballstats.eu/legenda.htm

Codigo Muestra
---
```
Select fc.*
From games g
Inner Join fielding_credits fc
On fc.gamePk = g.gamePk
Where g.seasonId = 2018
And majorLeagueId = 131;
```

**Comment by juanitobanca** [comment]
@junger92 , esta tarea es sencilla. Te ayudara a relacionarte con las tablas :)

**Comment by andres-alvarado** [comment]
Estadisticas que podemos calcular:
http://m.mlb.com/glossary/standard-stats
https://sabr.org/journal/article/measuring-defense-entering-the-zones-of-fielding-statistics/
http://www.espn.com/mlb/stats/fielding/_/order/true
https://gamechanger.zendesk.com/hc/en-us/articles/214493683-Stats-for-Batting-Pitching-Fielding-Catching
https://www.sportsbettingdime.com/guides/resources/baseball-stat-abbreviations/
https://www.baseballstats.eu/legenda.htm
