### ISSUE TITLE
Especificar usuario a crear durante instalacion

### ISSUE THREAD

**Issue by IvanVC21** [andres-alvarado/beisbol-analitica#55]
Especificar que durante la Instalacion de la Base de Datos de la wiki que se debe crear el usuario "juanito" con password "banca".

**Comment by juanitobanca** [comment]
Listo. Puedes revisarlo? https://github.com/andres-alvarado/beisbol-analitica/wiki/Instalaci%C3%B3n-de-la-Base-de-Datos.#install-database-windows

Si todo se ve bien, porfa cierra el issue, sino hazme saber tu retroalimentaciom.

**Comment by IvanVC21** [comment]
Listo. Muchas gracias!
