### ISSUE TITLE
Modificar instruccion de creacion de usuario en wiki

### ISSUE THREAD

**Issue by IvanVC21** [andres-alvarado/beisbol-analitica#56]
En la parte de Instalacion de la Base de Datos de la wiki viene la forma de crear usuario como: -u juanito -p banca; siendo que la forma correcta es: -ujuanito -pbanca

**Comment by juanitobanca** [comment]
Listo: https://github.com/andres-alvarado/beisbol-analitica/wiki/Instalaci%C3%B3n-de-la-Base-de-Datos. Si todo se ve bien, porfa cierra el issue, sino, hazme saber tu retroalimentacion.

**Comment by IvanVC21** [comment]
Listo, muchas gracias!
