### ISSUE TITLE
Instruccion de dar privilegios a usuario 

### ISSUE THREAD

**Issue by IvanVC21** [andres-alvarado/beisbol-analitica#57]
Falta en la Instalacion de la Base de Datos de la wiki el agregar el paso de entrar como root y de `grant all privileges on *.* to 'juanito'@'localhost';` para poder realizar operaciones.

**Comment by juanitobanca** [comment]
Listo: https://github.com/andres-alvarado/beisbol-analitica/wiki/Instalaci%C3%B3n-de-la-Base-de-Datos.
 
Si se ve bien porfa cierra el issue, si no, hazme saber tu retroalimentacion.

**Comment by IvanVC21** [comment]
Listo, muchas gracias!
