### ISSUE TITLE
Especificar direccion de archivo para correr dump.sql

### ISSUE THREAD

**Issue by IvanVC21** [andres-alvarado/beisbol-analitica#58]
En la parte de Instalacion de la Base de Datos de la wiki hace falta especificar que a la hora de correr el archivo dump.sql hay que poner la direccion completa donde se encuentra el archivo, tipo:  `source DireccionDelArchivo/dump.sql;`

**Comment by juanitobanca** [comment]
Listo: https://github.com/andres-alvarado/beisbol-analitica/wiki/Instalaci%C3%B3n-de-la-Base-de-Datos.

Si se ve bien, porfa cierra el issue. Si no, hazme saber tu retroalimentacion

**Comment by IvanVC21** [comment]
Listo, muchas gracias!
