### ISSUE TITLE
Agregar proceso de instalacion de paquetes y tablas en wiki

### ISSUE THREAD

**Issue by IvanVC21** [andres-alvarado/beisbol-analitica#70]

**Comment by juanitobanca** [comment]
@IvanVC21 , revisa el siguiente wiki y hazme saber si le falta algo. Si todo esta bien hay que cerrar el issue.

https://github.com/andres-alvarado/beisbol-analitica/wiki/Instalaci%C3%B3n-de-Objetos-de-Base-de-Datos

**Comment by IvanVC21** [comment]
Todo claro, muchas gracias!
