### ISSUE TITLE
Agregar instrucciones para ejecucion de paquetes en wiki

### ISSUE THREAD

**Issue by IvanVC21** [andres-alvarado/beisbol-analitica#71]

**Comment by juanitobanca** [comment]
Ivan, Hazme saber si se ve bien. Dejame tu retraolimentacion si algo no esta bien explicado, de lo contrario cerremos el issue.

https://github.com/andres-alvarado/beisbol-analitica/wiki/Ejecuci%C3%B3n-de-Procedimientos

**Comment by IvanVC21** [comment]
Todo claro, muchas gracias!
