### ISSUE TITLE
Migración de la DB en MySQL a MariaDB

### ISSUE THREAD

**Issue by farinteractions** [andres-alvarado/beisbol-analitica#79]
Aunque en principio estas dos bases de datos son compatibles e "intercambiables", migrar de una a otra en las nuevas versiones tiene sus diferencias.

**Comment by juanitobanca** [comment]
@farinteractions podrias agregar mas contexto acerca de las diferencias?

**Comment by farinteractions** [comment]
A partir de MySQL 8, se introduce un nuevo formato de colación (_collation_) para el manejo de caracteres llamado _utf8mb4_0900_ai_ci_, el cual aún no es compatible con MariaDB 10. 
La colación indica el tamaño de bytes soportado, el algoritmo usado para comparar dos string tipo Unicode, y las consideraciones al manejar caracteres con acentos y mayúsculas (para una descripción más amplia visite [aquí]( https://www.monolune.com/what-is-the-utf8mb4_0900_ai_ci-collation/)).

Si se intenta cargar la base de datos directamente exportada de MySQL 8 a MariaDB se genera el siguiente error:
```
1273 – Unknown collation: ‘utf8mb4_0900_ai_ci’
```

## Migrando a MariaDB
Para migrar una base de datos exportada desde **MySQL 8** a **MariaDB 10**, primero hay que revisar el _character set_ y la _collation_ en la base de datos destino:
```SQL
MariaDB [(none)]> SHOW VARIABLES WHERE variable_name LIKE 'character_set_%' OR variable_name LIKE 'collation%';
```
La salida al anterior comando mostrará el _character_set_ con valores de `utf8mb4` y la _collation_ con`utf8mb4_general_ci`, indicando los soportados por default en MariaDB.

La _collation_ en el archivo exportado debe ajustarse a este valor para cada una de las tablas. Se recomienda, para hacer la edición del archivo más sencilla, que se exporte la DB en dos archivos, uno para la estructura y otro para los datos.
En la máquina con MySQL 8:
```
# mysqldump -u [user] -p --no-data [database] > dump_db_structure.sql
# mysqldump -u [user] -p --no-create-info [database] > dump_db_data.sql
```
Abrir el archivo _dump_db_structure.sql_ y editarlo, cambiando en cada descripción de las tablas
```
COLLATE=utf8mb4_0900_ai_ci;
```
por
```
COLLATE=utf8mb4_general_ci;
```
Una vez editado el archivo, llevarlo a la máquina con MariaDB instalado y continuar los pasos descritos [aquí](https://github.com/andres-alvarado/beisbol-analitica/wiki/Instalaci%C3%B3n-de-la-Base-de-Datos.), primero corriendo para el archivo de la estructura y luego para el de los  datos.

**Comment by juanitobanca** [comment]
Gracias @farinteractions
