### ISSUE TITLE
[ DOCUMENTACION ] Manual para descarga e instalacion de la base de datos

### ISSUE THREAD

**Issue by juanitobanca** [andres-alvarado/beisbol-analitica#8]
Resumen
---
Ahora que vamos a compartir el repositorio de datos, debemos enseñar a la gente a como instalarla. Debemos crear un manual facil que le explique al usuario como descargar la base de datos( data/dump/dump.sql ) en MySQL 8+. El manual debe situarse en el wiki del proyecto.

Tareas Relacionadas
---
[ DOCUMENTACION ] Como descargar e instalar MySQL #9
[ DOCUMENTACION ] Conectarse a MySQL y ejecutar queries #10

**Comment by juanitobanca** [comment]
Asignando a @junger92, @farinteractions y @omargoldpr  ya que tienen atravesar este proceso. Una vez instalado mysql hay que seguir los siguientes pasos desde un terminal:

1. Crear Usuario( por medio de usuario root ):
```
mysql> CREATE USER 'juanito'@'localhost' IDENTIFIED BY 'banca';
```

2. Logearse a mysql con el nuevo usuario:
```
$ mysql -u juanito -pbanca;
```

3. Crear la Base de Datos:
```
mysql> create database baseball;
```

4. Cargar el archivo dump.sql que se encuentra en data/dump/dump.sql:
```
mysql> source dump.sql
```

**Comment by junger92** [comment]
en el paso 4 Cargar el archivo dump.sql que se encuentra en data/dump/dump.sql estoy obteniendo el siguiente error:
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'version https://git-lfs.github.com/spec/v1
oid sha256:3736ab0be5694338d91772cb00' at line 1

**Comment by juanitobanca** [comment]
> en el paso 4 Cargar el archivo dump.sql que se encuentra en data/dump/dump.sql estoy obteniendo el siguiente error:
> ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'version https://git-lfs.github.com/spec/v1
> oid sha256:3736ab0be5694338d91772cb00' at line 1

Hay otra informacion aparte de esta? Que pasa si comentas la linea 1?

**Comment by juanitobanca** [comment]
Empezada la documentacion en: https://github.com/andres-alvarado/beisbol-analitica/wiki/Instalaci%C3%B3n-de-la-Base-de-Datos

**Comment by juanitobanca** [comment]
Creada: https://github.com/andres-alvarado/beisbol-analitica/wiki/Instalaci%C3%B3n-de-la-Base-de-Datos.
