### ISSUE TITLE
[BATEO] Calcular OPS+

### ISSUE THREAD

**Issue by juanitobanca** [andres-alvarado/beisbol-analitica#92]
Descripcion
---
Utilizar unicamente agg_batting_stats:

Recursos
---
Se puede encontrar la formula en baseballreference.
https://www.baseball-reference.com/players/w/willite01.shtml

**Comment by junger92** [comment]
hola, cuando pruebo el procedimiento agg_batting_stats me está dando este erro
r01:13:27	CALL agg_batting_stats( 'majorLeagueId', @insert_stmt )	Error Code: 1054 Unknown column 'stolenBaseAttempts' in 'field list'	
el campo stolenBaseAttempts falta en la definicion de la tabla agg_batting_stats.

**Comment by juanitobanca** [comment]
> hola, cuando pruebo el procedimiento agg_batting_stats me está dando este erro
> r01:13:27 CALL agg_batting_stats( 'majorLeagueId', @insert_stmt ) Error Code: 1054 Unknown column 'stolenBaseAttempts' in 'field list'
> el campo stolenBaseAttempts falta en la definicion de la tabla agg_batting_stats.

Profe, ahora mismo lo arreglo. y subo el nuevo codigo.

**Comment by juanitobanca** [comment]
@junger92, actualizadas las tablas, puedes recrearlas y hacer el call de nuevo.

**Comment by junger92** [comment]
gracias!!
